### ISSUE TITLE
Add license to Conventions

### ISSUE THREAD

**Issue by erget** [cf-convention/cf-convention.github.io#182]
_Originally posted by @bnlawrence in https://github.com/cf-convention/cf-convention.github.io/issues/116#issuecomment-645891182_

> I started writing about this a while ago, and got distracted. Anyway, wrt license/privacy notice, I think we should use a CC license (probably [this one](https://creativecommons.org/share-your-work/public-domain/cc0/)). We're not a legal entity and don't want to be one, so it's not obvious that we need to bother with any attribution of rights *to* us. We might, if we were paranoid, require all pull requests to include something like the following at the bottom of the explanation:
> 
> I certify that I wrote this content and/or otherwise have the right to pass it on into this documentation where it will be covered by [insert our cc license]

I agree, we should explore this.

**Comment by ethanrd** [comment]
Hi all - Along with license, I think it might be important to consider copyright.

I've seen a number of open source software and document projects assigning copyright to “_project-name_ Developers” or “_project-name_ Developers and Contributors” or “_project-name_ Community”.

That seems like a good model for CF but I was never quite sure what it really meant. Project Jupyter marks their copyright as "Project Jupyter Developers" and explains their copyright policy, on their [license page](https://github.com/jupyter/governance/blob/master/projectlicense.md), as a shared copyright model, where the overall copyright is held by the community but individual contributors maintain the copyright over their individual contributions.

**Comment by ethanrd** [comment]
In terms of getting permission from all authors to change the license, another project I work on was advised to do a "best effort" attempt to notify all authors and allow time for objections rather than needing explicit permission from all authors (which may be very hard to get).

On the other hand, I wonder if that would apply if we wanted to change to CC0 which, if I understand it, explicitly relinquishes copyright. That seems like a bigger hurdle.

**Comment by erget** [comment]
@ethanrd +1 on best effort with reasonable deadline. This would be similar to changes with the 6-week rule.

WRT the copyright holders, my preferred terminology would be "Community", because the community as a whole contributes, not only individual authors. Although git would make it possible to track individual contributions, the Conventions have been around a long time and will hopefully stick around for even longer, so my preference would be for contributors to be credited but relinquish their copyright upon submission. From a work perspective it'd be no difference, in my opinion, but we'd need to document it in the contribution guidelines. What do you think?

**Comment by HeinkeH** [comment]
I have already commented on the licenses. But I agree with any license you choose.

**Comment by sadielbartholomew** [comment]
To add, regarding license choice the site [choosealicense.com](https://choosealicense.com/) is really useful.

**Comment by larsbarring** [comment]
Sorry for coming late to the party, but earlier today during the hackaton session on license and doi the following crossed my mind:

With CC0 we do not claim any copyrights. This would allow someone to grab all of the CF website content and just republish it as say cfconventions.net, and then add commercial banners and similar. And, as the CF website is a popular one that generates a lot of traffic it is also vulnerable to copycats wanting to take advantage of this to generate click income for themselves. With CC0 we basically allow this without complaints. Although with a license that retains copyrights we do not foresee sending lawyers after the copycats, but we at least make it clear that this is acceptable.

Just a thought, otherwise I do not have any views regarding the license.

**Comment by martinjuckes** [comment]
I support the proposal to add an explicit license statement to the CF Conventions document and, for consistency, I feel that it would make sense to use the same license on the CF standard name table.

According to this post https://opensource.guide/legal/ , contributors hold copyright to the parts that they contribute unless there is an explicit declaration. This would mean that anybody wishing to quote bits of the convention in risk-averse journal might be required to get permission from responsible contributors .... adding a license would make the situation clearer.

Using "CC BY" and requiring people to fully cite the CF convention every time they use it would be quite disruptive (e.g. making it illegal to use CF metadata in a file without providing a citation). The authors of the [latest version of HTML](https://html.spec.whatwg.org/multipage/acknowledgements.html#ipr) get around this with the following text:

> This work is licensed under a [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0/). To the extent portions of it are incorporated into source code, such portions in the source code are licensed under the [BSD 3-Clause License](https://opensource.org/licenses/BSD-3-Clause) instead.

With this approach, people using the standard in code do not need to provide attribution. I don't have a strong view, but using a mixed approach, rather than CC0, would avoid the concern raised by Lars and does not appear difficult to implement.

I've been told by someone who understands these things better than me that "CC0" is not a license, it is a "Deed".  The distinction appears to be that a license sets up obligations for the licensee, but a deed simply makes an assertion and implies no obligations on the user. I'm not sure it this matters .. it is widely referred to as a license.

**Comment by ethanrd** [comment]
Hi all - While there were some comments, there were no objections to the CF Governance Panel decision to license CF with [CC0](https://creativecommons.org/publicdomain/zero/1.0/). So we will move forward with implementing CC0 for CF.

Here are the three next steps I came up with:

- Create a LICENSE.md file in both the Conventions repo and the Website repo.
- Add a license mark to the generated Conventions documents
- Add a license mark to the footer of each website page

I will create PR(s) to add the LICENSE.md files and look into how to add the license to the web pages. Lars @larsbarring and David @davidhassell, do you have an idea of how to add the license to the Conventions documents?

Any other suggestions for steps that might be needed?

**Comment by davidhassell** [comment]
Hi Ethan,

I think it's as simple just merging the PR https://github.com/cf-convention/cf-conventions/pull/504 - GitHub will know that it's a license from the file name, and will glean which license from the contents. I tested this at https://github.com/davidhassell/delme.

**Comment by larsbarring** [comment]
Hi Ethan, 
I can look into -- and probably fix -- the second bullet point. But it will take a couple of weeks or so, because I am currently digging into the different versions of the standard name table. Fixing the pdf version should be simple (I hope), but I do not know about the html version because that basically is just one long document with no pages.

**Comment by larsbarring** [comment]
Regarding the third bullet point
> • Add a license mark to the footer of each website page


it seems like a simple addition to the `__layouts/default.html` file is needed. The footer now looks like this (screen clip image):

-------------------
![image](https://github.com/cf-convention/cf-convention.github.io/assets/15440426/42da8335-f1ba-46b3-8ab2-766ca32b096d)

-------------------

The bottom line could just be changed to read something like 

"This site is open source in line with [Creative Commons Zero CC0](https://creativecommons.org/publicdomain/zero/1.0/) . &nbsp;&nbsp;[Improve this page!](https://github.com/cf-convention/cf-convention.github.io/edit/main/index.md)

**Comment by ethanrd** [comment]
Hi Lars @larsbarring - That sounds really good for the website (3rd bullet item). For the convention (2nd bullet item), I wonder if just adding another line below the title, author, version at the top of the conventions document (in `cf-conventions.adoc`) would be enough. It would cover both the HTML and PDF versions.

**Comment by larsbarring** [comment]
Thanks Ethan @ethanrd. I have just created a PR (despite being a html noob), and added you as reviewer. And I will have a go at the second bullet item in the coming days.

**Comment by larsbarring** [comment]
The last addition to PR #461 was done on March 16 (addition of CC0 logo), which means that the PR can be merged on April 8, if there are no more comments.

**Comment by JonathanGregory** [comment]
Thanks very much, @larsbarring. You would be able to see the full result, I think, if you publish your branch to the web via GitHub Pages in your repo.

**Comment by larsbarring** [comment]
Thanks @JonathanGregory, this was news to me! 

But it also showed that there is a problem with the  badge/logo, which now shows up as broken. I have tried different alternatives without success. As I wrote above (7 March) my html skills are just about zero, so I give up this attempt and leave it to others to fix. But I imagine that for more someone more familiar with html it will be a very quick fix.

**Comment by larsbarring** [comment]
In PR #461  I have now removed the CCO logo badge from the footer file and now it works as expected (see [here])(https://larsbarring.github.io/cf-convention.github.io/). This is pretty much what I [suggested](https://github.com/cf-convention/cf-convention.github.io/issues/182#issuecomment-1983550340), which received [support](https://github.com/cf-convention/cf-convention.github.io/issues/182#issuecomment-1984178191). 

Hence, could someone merge PR #461.

**Comment by JonathanGregory** [comment]
@ethanrd [wrote](https://github.com/cf-convention/cf-convention.github.io/issues/182#issuecomment-1901198732)

> Here are the three next steps I came up with:
> 
> * Create a LICENSE.md file in both the Conventions repo and the Website repo.
> * Add a license mark to the generated Conventions documents
> * Add a license mark to the footer of each website page

Ethan did the first action. The second one is being dealt with by @larsbarring in [conventions issue 513](https://github.com/cf-convention/cf-conventions/issues/513). Lars's PR https://github.com/cf-convention/cf-convention.github.io/pull/461 will achieve the last action. I will merge Lars's PR now, and thereby close this issue. Thanks, Lars, Ethan et al.
