### ISSUE TITLE
Broken link to NUG reference

### ISSUE THREAD

**Issue by atmodatcode** [cf-convention/cf-convention.github.io#190]
Hello, 

I discovered broken hyperlinks to the NUG reference. They point to 
https://www.unidata.ucar.edu/software/netcdf/docs/user_guide.html
while the correct link is now
https://www.unidata.ucar.edu/software/netcdf/documentation/NUG/

Here are the places where I discovered broken links:
1.2. Terminology
CDL syntax   
--> see NUG section on CDL syntax

2.5.1. Missing data, valid and actual range of data
--> NUG Appendix A, Attribute Conventions
--> NUG Appendix B, File Format Specifications

Table A.1. Attributes
--> many broken  NUG Appendix A, "Attribute Conventions" links in table 

Bibliography
References
--> [NUG] The NetCDF User’s Guide

Best regards
Angelika

**Comment by JonathanGregory** [comment]
Dear @atmodatcode 

Thanks for pointing out these broken links and sorry that no-one replied to you. The ones in 2.5.1 and Appendix A.1 have been fixed in the [latest release](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.10/cf-conventions.html) but the others are still there. They can maybe still be fixed since the release has only just been compiled. I'll repost your comment in the [currently open issue #169 in the discuss repo](https://github.com/cf-convention/discuss/issues/169) about the latest release.

Jonathan
