### ISSUE TITLE
remove douplicate orphan pages

### ISSUE THREAD

**Issue by neumannd** [cf-convention/cf-convention.github.io#212]
There are three pages on cfconventions.org which can be found via search machines but which cannot be accessed via internal references. Additionally, the content of these pages in present on other pages, which are accessible.

* [conformance.md](https://github.com/cf-convention/cf-convention.github.io/blob/main/conformance.md): no link pointing to it; content also present in [conventions.md](https://github.com/cf-convention/cf-convention.github.io/blob/main/conventions.md)
* [requirements-and-recommendations.md](https://github.com/cf-convention/cf-convention.github.io/blob/main/requirements-and-recommendations.md): child of [conformance.md](https://github.com/cf-convention/cf-convention.github.io/blob/main/conformance.md); content also present in [conventions.md](https://github.com/cf-convention/cf-convention.github.io/blob/main/conventions.md)
* [compliance-checker.md](https://github.com/cf-convention/cf-convention.github.io/blob/main/compliance-checker.md): child of [conformance.md](https://github.com/cf-convention/cf-convention.github.io/blob/main/conformance.md); content also present in [software.md](https://github.com/cf-convention/cf-convention.github.io/blob/main/software.md)

**Comment by erget** [comment]
Hi @neumannd good find, would you be willing to open a PR to remove these?

**Comment by neumannd** [comment]
@erget Fast reply 👍 . Yes, sure.

**Comment by neumannd** [comment]
pushed PR #213 . Unfortunately, one check failed. It does not seem to be related to the changes I did.

**Comment by erget** [comment]
That looks good to me and thanks @JonathanGregory for also having a look! As an aside, my personal preference is to remove obsoleted items immediately if they have no function, because they're still available via the magic of git. If we should decide to restore them and remove them at the moment they become obsolete, we would be able to trace their removal to the change that made them obsolete. Of course, reality is often more complicated than that and it's not necessarily clear what becomes obsolete and when, but it's always a comfort to me to know that git can recover what I deleted if I get overzealous.

Merging #213 with thanks to @neumannd - looks like you're on a cleaning spree, I like it :)

**Comment by erget** [comment]
> pushed PR #213 . Unfortunately, one check failed. It does not seem to be related to the changes I did.

Yes, that check fails because we have outbound links that are unreachable - need to do a thorough scrub of the website but nobody's had time to do it yet.
