### ISSUE TITLE
Broken link to COARDS convention.

### ISSUE THREAD

**Issue by martinjuckes** [cf-convention/cf-convention.github.io#74]
The link to the COARDS Convention from the cfconventions.org home page is broken ... it should be https://ferret.pmel.noaa.gov/noaa_coop/coop_cdf_profile.html (the domain name has changed).

**Comment by sadielbartholomew** [comment]
Hi @martinjuckes,

I just noticed an equivalent broken link within the ``cf-convention/cf-conventions`` repo whilst I was exploring & reading through it, & I'm about to raise a PR there to fix it. Just to register here that the link from the same amended host, but with a slightly-different full path (which has changed relative to the original), 'https://ferret.pmel.noaa.gov/Ferret/documentation/coards-netcdf-conventions' seems more appropriate that the one you suggest above, since:

* it's a page directly under the NOAA site sitemap;
* it's rendered fully in CSS whereas your link gives a plain HTML page which suggests it isn't a key page; &
* it seems more official from the keyword components in the link.

For that reason in my PR I'll amend the link to that above in the ```cf-conventions`` repo, & a consistent link should ideally be used here when updated.
