### ISSUE TITLE
Need direct links to latest CF Convention document in html

### ISSUE THREAD

**Issue by ngalbraith** [cf-convention/cf-convention.github.io#82]
I'm working on an update to guidelines for data providers in the OceanSITES project. We refer to the CF convention many times in the document, and sometimes to specific chapters. It would be great if these links could point directly to the most recent version of the document.

There's a handy page at http://cfconventions.org/latest.html, but I can't seem to get to the latest conventions document in html via a direct link, as far as I can tell. Since I want people to actually read the CF doc, I really want to limit the clicks they need to go through. And, I don't want to risk sending people to old versions of the document.

At the moment I'm trying to link to the latest on discrete sampling geometries, cf-conventions.html#discrete-sampling-geometries, which is now in /Data/cf-conventions/cf-conventions-1.7.  

Is there actually a URL that will point directly to the most recent conventions document, in html?

**Comment by graybeal** [comment]
I'm pretty sure we've never attempted that.   I agree it would be nice.

What it would take, as far as I'm aware, is an Apache rewrite pattern capable of replacing 'latest' in any such URLs with the actual latest version, e.g., 1.7 in this case:
`http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#discrete-sampling-geometries`

The problem is, it would lock in all future CF documents to follow the same naming/anchoring strategies, so you couldn't ever rename Discrete Sampling Geometries to, say, Discrete Sampling Shapes. The solution to that would be to manually create redirects from old anchors, so the rewrite rule would first correct the old path `#discrete-sampling-geometries` to the new path, then would correct `latest` to `cf-conventions-1.7`, or whatever. 

Keeping in mind the last time there were major changes in heading might be a decade ago (so, it wouldn't be super-expensive to add this feature), I agree it would be really nice if the team maintaining the CF site had agile enough devops practices to support it. But in my experience this is often not practical, depending on how things are organized on the sys admin side. So I'm not getting my hopes up too high.

**Comment by ngalbraith** [comment]
Depending on the server, the 'latest' directory might be a symbolic link to wherever the latest document is, in which case the cf-conventions-1.7 directory could be linked to 'current' until 1.8 is released. 

As for the anchor for the Discrete Sampling Geometries section, if the term changes, we would be updating the OS format reference to reflect that change anyway. Or, the anchor could be maintained, no matter what the displayed text is. If that's not an option, at least folks would be in the correct document, since a missing/incorrect  anchor just leaves you at the top of the page.

**Comment by erget** [comment]
http://cfconventions.org/cf-conventions/cf-conventions.html points to the latest working draft. Is that what you're looking for or are you wanting the latest approved version?

**Comment by erget** [comment]
@graybeal concerning your thought I agree - in fact it's a handy design principal of asciidocs that the anchor's name is independent of the text that you find when you navigate to it. So in principal we could change the name of headings but we should be very cautious to change anchor names associated with headings.

As we're hosting on Github Pages we also wouldn't need to use anything as fancy as an Apache directive - we could just set a symbolic link, I believe, and include the updating of that link in the update checklist.

**Comment by graybeal** [comment]
Oooh, I didn't realize GitHub pages could do symbolic links. Yes we should definitely try that with just the main URL, from 'latest' to the 1.7 version, and see if that works. 

If it does, we may get the section-by-section for free, which is what I think Nan really wants. 

I was assuming the section headers were auto-generated based on the section titles used in the headers, many wiki sites work that way. If that's true we'd just have to manually add a header manually whenever the title changed.  I think this would be worth it, on the Berners-Lee principal 'old URLs should never die'.   (I ran into this wish of Nan's a while ago but I think it wasn't feasible then, so maybe I'm biased!)

**Comment by ngalbraith** [comment]
Daniel - 
> http://cfconventions.org/cf-conventions/cf-conventions.html points to the latest working draft. Is that what you're looking for or are you wanting the latest approved version?

Yes, thank you, that's exactly what I was looking for!  On the main CF page, cfconventions.org, there's a link to http://cfconventions.org/latest.html, and the only link I could find there to the most recent version (without the actual version number in the URL) pointed to an intermediate page. 

Maybe somewhere on the site we could include text to the effect that cfconventions.org/cf-conventions/cf-conventions.html always contains the text of the current version.

Other than that, I think this issue could be closed. Thanks all!

**Comment by erget** [comment]
@ngalbraith I've added a note to the page like you suggested. Thanks for the feedback :)
